[project]
name = "access_mgmt_tool"
description = "Access Management Tool"
version = "0.1"

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -q -p no:warnings --reuse-db"
DJANGO_SETTINGS_MODULE = "config.settings"
testpaths = [
    "tests/",
]
