# Generated by Django 4.0.5 on 2022-06-07 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(help_text='The dotted path to the ingregration class', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField()),
                ('description', models.TextField()),
                ('configuration', models.JSONField()),
                ('active', models.BooleanField(default=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.integration')),
            ],
        ),
    ]
