# Generated by Django 4.0.5 on 2022-06-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='configuration',
            field=models.JSONField(null=True),
        ),
    ]
