# Generated by Django 4.0.5 on 2022-06-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_application_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='configuration',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
