# Generated by Django 4.0.5 on 2022-06-07 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_accessrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessRequest',
        ),
    ]
