# Generated by Django 4.0.5 on 2022-06-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrequest',
            name='permissions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
